[2025-09-25T19:09:33.951+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T19:09:34.027+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: robot_powershell_host_run.run_robot_tests manual__2025-09-25T19:09:32.587034+00:00 [queued]>
[2025-09-25T19:09:34.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: robot_powershell_host_run.run_robot_tests manual__2025-09-25T19:09:32.587034+00:00 [queued]>
[2025-09-25T19:09:34.045+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-25T19:09:34.068+0000] {taskinstance.py:2330} INFO - Executing <Task(WinRMOperator): run_robot_tests> on 2025-09-25 19:09:32.587034+00:00
[2025-09-25T19:09:34.085+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=283) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-25T19:09:34.089+0000] {standard_task_runner.py:64} INFO - Started process 284 to run task
[2025-09-25T19:09:34.085+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'robot_powershell_host_run', 'run_robot_tests', 'manual__2025-09-25T19:09:32.587034+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/robot_powershell_winrm.py', '--cfg-path', '/tmp/tmpsn3dk4f3']
[2025-09-25T19:09:34.091+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask run_robot_tests
[2025-09-25T19:09:34.235+0000] {task_command.py:426} INFO - Running <TaskInstance: robot_powershell_host_run.run_robot_tests manual__2025-09-25T19:09:32.587034+00:00 [running]> on host dc041d20e279
[2025-09-25T19:09:34.436+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='robot_powershell_host_run' AIRFLOW_CTX_TASK_ID='run_robot_tests' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T19:09:32.587034+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T19:09:32.587034+00:00'
[2025-09-25T19:09:34.437+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T19:09:34.505+0000] {winrm.py:80} INFO - Hook not found, creating...
[2025-09-25T19:09:34.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T19:09:34.548+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/microsoft/winrm/operators/winrm.py", line 92, in execute
    winrm_client = self.winrm_hook.get_conn()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/microsoft/winrm/hooks/winrm.py", line 131, in get_conn
    conn = self.get_connection(self.ssh_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `winrm_localhost` isn't defined
[2025-09-25T19:09:34.556+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=robot_powershell_host_run, task_id=run_robot_tests, run_id=manual__2025-09-25T19:09:32.587034+00:00, execution_date=20250925T190932, start_date=20250925T190934, end_date=20250925T190934
[2025-09-25T19:09:34.575+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task run_robot_tests (The conn_id `winrm_localhost` isn't defined; 284)
[2025-09-25T19:09:34.629+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T19:09:34.666+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T19:09:34.669+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
